### ISSUE TITLE
Issue on Start-Up which disabled the plugin

### ISSUE THREAD

**Issue by morgan2233** [clickpt/EasySetSpawn#9]
```
[15:08:37] [Server thread/INFO]: [EasySetSpawn] Enabling EasySetSpawn v3.3*
[15:08:37] [Server thread/ERROR]: Error occurred while enabling EasySetSpawn v3.3 (Is it up to date?)
java.lang.NullPointerException: null
	at me.clickpt.easysetspawn.Main.onEnable(Main.java:42) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-466]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:08:37] [Server thread/INFO]: [EasySetSpawn] Disabling EasySetSpawn v3.3
[15:08:37] [Server thread/INFO]: [EasySetSpawn] Disabled!
```

Paper-Spigot 1.16.5

**Comment by clickpt** [comment]
Hi!
Can you show your config.yml file from EasySetSpawn?
